name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Build and deploy
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: .
